
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.config
{
public partial class Tbbullets
{
    private readonly System.Collections.Generic.Dictionary<int, config.bullets> _dataMap;
    private readonly System.Collections.Generic.List<config.bullets> _dataList;
    
    public Tbbullets(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, config.bullets>(n);
        _dataList = new System.Collections.Generic.List<config.bullets>(n);
        for(int i = n ; i > 0 ; --i)
        {
            config.bullets _v;
            _v = global::cfg.config.bullets.Deserializebullets(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, config.bullets> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<config.bullets> DataList => _dataList;

    public config.bullets GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public config.bullets Get(int key) => _dataMap[key];
    public config.bullets this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

