
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.config
{
public partial class Tbprop
{
    private readonly System.Collections.Generic.Dictionary<int, config.prop> _dataMap;
    private readonly System.Collections.Generic.List<config.prop> _dataList;
    
    public Tbprop(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, config.prop>(n);
        _dataList = new System.Collections.Generic.List<config.prop>(n);
        for(int i = n ; i > 0 ; --i)
        {
            config.prop _v;
            _v = global::cfg.config.prop.Deserializeprop(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, config.prop> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<config.prop> DataList => _dataList;

    public config.prop GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public config.prop Get(int key) => _dataMap[key];
    public config.prop this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

