
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public config.Tbprop Tbprop {get; }
    public config.Tbbullets Tbbullets {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        Tbprop = new config.Tbprop(loader("config_tbprop"));
        Tbbullets = new config.Tbbullets(loader("config_tbbullets"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tbprop.ResolveRef(this);
        Tbbullets.ResolveRef(this);
    }
}

}
